#line 1 "dubya.c"

#line 3 "dubya.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer dubya_yy_create_buffer
#define yy_delete_buffer dubya_yy_delete_buffer
#define yy_scan_buffer dubya_yy_scan_buffer
#define yy_scan_string dubya_yy_scan_string
#define yy_scan_bytes dubya_yy_scan_bytes
#define yy_init_buffer dubya_yy_init_buffer
#define yy_flush_buffer dubya_yy_flush_buffer
#define yy_load_buffer_state dubya_yy_load_buffer_state
#define yy_switch_to_buffer dubya_yy_switch_to_buffer
#define yypush_buffer_state dubya_yypush_buffer_state
#define yypop_buffer_state dubya_yypop_buffer_state
#define yyensure_buffer_stack dubya_yyensure_buffer_stack
#define yy_flex_debug dubya_yy_flex_debug
#define yyin dubya_yyin
#define yyleng dubya_yyleng
#define yylex dubya_yylex
#define yylineno dubya_yylineno
#define yyout dubya_yyout
#define yyrestart dubya_yyrestart
#define yytext dubya_yytext
#define yywrap dubya_yywrap
#define yyalloc dubya_yyalloc
#define yyrealloc dubya_yyrealloc
#define yyfree dubya_yyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define dubya_yy_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer dubya_yy_create_buffer
#endif

#ifdef yy_delete_buffer
#define dubya_yy_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer dubya_yy_delete_buffer
#endif

#ifdef yy_scan_buffer
#define dubya_yy_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer dubya_yy_scan_buffer
#endif

#ifdef yy_scan_string
#define dubya_yy_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string dubya_yy_scan_string
#endif

#ifdef yy_scan_bytes
#define dubya_yy_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes dubya_yy_scan_bytes
#endif

#ifdef yy_init_buffer
#define dubya_yy_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer dubya_yy_init_buffer
#endif

#ifdef yy_flush_buffer
#define dubya_yy_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer dubya_yy_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define dubya_yy_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state dubya_yy_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define dubya_yy_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer dubya_yy_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define dubya_yypush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state dubya_yypush_buffer_state
#endif

#ifdef yypop_buffer_state
#define dubya_yypop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state dubya_yypop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define dubya_yyensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack dubya_yyensure_buffer_stack
#endif

#ifdef yylex
#define dubya_yylex_ALREADY_DEFINED
#else
#define yylex dubya_yylex
#endif

#ifdef yyrestart
#define dubya_yyrestart_ALREADY_DEFINED
#else
#define yyrestart dubya_yyrestart
#endif

#ifdef yylex_init
#define dubya_yylex_init_ALREADY_DEFINED
#else
#define yylex_init dubya_yylex_init
#endif

#ifdef yylex_init_extra
#define dubya_yylex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra dubya_yylex_init_extra
#endif

#ifdef yylex_destroy
#define dubya_yylex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy dubya_yylex_destroy
#endif

#ifdef yyget_debug
#define dubya_yyget_debug_ALREADY_DEFINED
#else
#define yyget_debug dubya_yyget_debug
#endif

#ifdef yyset_debug
#define dubya_yyset_debug_ALREADY_DEFINED
#else
#define yyset_debug dubya_yyset_debug
#endif

#ifdef yyget_extra
#define dubya_yyget_extra_ALREADY_DEFINED
#else
#define yyget_extra dubya_yyget_extra
#endif

#ifdef yyset_extra
#define dubya_yyset_extra_ALREADY_DEFINED
#else
#define yyset_extra dubya_yyset_extra
#endif

#ifdef yyget_in
#define dubya_yyget_in_ALREADY_DEFINED
#else
#define yyget_in dubya_yyget_in
#endif

#ifdef yyset_in
#define dubya_yyset_in_ALREADY_DEFINED
#else
#define yyset_in dubya_yyset_in
#endif

#ifdef yyget_out
#define dubya_yyget_out_ALREADY_DEFINED
#else
#define yyget_out dubya_yyget_out
#endif

#ifdef yyset_out
#define dubya_yyset_out_ALREADY_DEFINED
#else
#define yyset_out dubya_yyset_out
#endif

#ifdef yyget_leng
#define dubya_yyget_leng_ALREADY_DEFINED
#else
#define yyget_leng dubya_yyget_leng
#endif

#ifdef yyget_text
#define dubya_yyget_text_ALREADY_DEFINED
#else
#define yyget_text dubya_yyget_text
#endif

#ifdef yyget_lineno
#define dubya_yyget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno dubya_yyget_lineno
#endif

#ifdef yyset_lineno
#define dubya_yyset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno dubya_yyset_lineno
#endif

#ifdef yywrap
#define dubya_yywrap_ALREADY_DEFINED
#else
#define yywrap dubya_yywrap
#endif

#ifdef yyalloc
#define dubya_yyalloc_ALREADY_DEFINED
#else
#define yyalloc dubya_yyalloc
#endif

#ifdef yyrealloc
#define dubya_yyrealloc_ALREADY_DEFINED
#else
#define yyrealloc dubya_yyrealloc
#endif

#ifdef yyfree
#define dubya_yyfree_ALREADY_DEFINED
#else
#define yyfree dubya_yyfree
#endif

#ifdef yytext
#define dubya_yytext_ALREADY_DEFINED
#else
#define yytext dubya_yytext
#endif

#ifdef yyleng
#define dubya_yyleng_ALREADY_DEFINED
#else
#define yyleng dubya_yyleng
#endif

#ifdef yyin
#define dubya_yyin_ALREADY_DEFINED
#else
#define yyin dubya_yyin
#endif

#ifdef yyout
#define dubya_yyout_ALREADY_DEFINED
#else
#define yyout dubya_yyout
#endif

#ifdef yy_flex_debug
#define dubya_yy_flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug dubya_yy_flex_debug
#endif

#ifdef yylineno
#define dubya_yylineno_ALREADY_DEFINED
#else
#define yylineno dubya_yylineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define dubya_yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 82
#define YY_END_OF_BUFFER 83
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[197] =
    {   0,
       83,   81,   82,   80,   81,   82,   82,   64,   81,   82,
       81,   82,   64,   81,   82,   64,   81,   82,   64,   81,
       82,   64,   81,   82,   64,   81,   82,   64,   81,   82,
       64,   81,   82,   64,   81,   82,   64,   81,   82,   64,
       81,   82,   64,   81,   82,   64,   81,   82,   64,   81,
       82,   64,   81,   82,   64,   81,   82,   64,   81,   82,
       64,   81,   82,   64,   81,   82,   64,   81,   82,   64,
       81,   82,   64,   81,   82,   64,   81,   82,   64,   81,
       82,   64,   81,   82,   79,   81,   82,   79,   80,   81,
       82,   79,   82,   79,   81,   82,   77,   79,   81,   82,

       81,   82,   81,   82,   81,   82,   81,   82,   81,   82,
       81,   82,   78,    1,   66,   69,   65,   41,   41,16419,
       31,   29,   71,   67,   72,   76,   74,   73, 8227,   21,
       32,   10,16421,    3,16420,16418,    7,   54,   63, 8229,
       42,   43, 8228, 8226,   68,   70,   75,   38,    6,   50,
       56,   11,   25,   45,   24,   62,   46,   18,   57,   16,
       22,   14,   55,    4,   12,   49,    2,   39,   26,   61,
       27,   20,   44,   13,   51,   58,16417,   19,16414,   15,
       17, 8225,   48,    5, 8222,   23,   59,    8,    9,   47,
       60,   52,   53,16424, 8232,   28

    } ;

static const flex_int16_t yy_accept[541] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    4,    7,
        8,   11,   13,   16,   19,   22,   25,   28,   31,   34,
       37,   40,   43,   46,   49,   52,   55,   58,   61,   64,
       67,   70,   73,   76,   79,   82,   85,   88,   92,   94,
       97,  101,  103,  105,  107,  109,  111,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  114,  114,  114,  114,  114,

      114,  114,  114,  114,  114,  114,  114,  115,  115,  115,
      115,  115,  115,  115,  115,  115,  115,  115,  115,  115,
      115,  115,  115,  115,  115,  115,  115,  115,  115,  115,
      115,  115,  115,  115,  115,  115,  115,  115,  115,  115,
      115,  115,  115,  115,  115,  115,  115,  115,  115,  115,
      115,  115,  115,  115,  115,  115,  115,  115,  115,  115,
      116,  116,  116,  117,  117,  117,  118,  118,  118,  118,
      118,  118,  118,  119,  120,  120,  120,  120,  120,  120,
      120,  121,  121,  121,  121,  121,  121,  121,  121,  121,
      121,  121,  121,  121,  121,  121,  121,  121,  121,  122,

      122,  122,  122,  122,  122,  122,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  124,  125,  125,  125,  126,
      127,  128,  128,  129,  129,  129,  129,  129,  129,  129,
      129,  129,  129,  130,  130,  130,  130,  130,  130,  130,
      130,  130,  130,  130,  130,  130,  130,  130,  130,  131,
      132,  133,  133,  133,  134,  134,  134,  134,  134,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  136,
      137,  137,  137,  137,  138,  138,  139,  139,  139,  139,
      139,  139,  139,  139,  139,  139,  139,  139,  139,  139,

      139,  139,  139,  139,  139,  139,  139,  139,  139,  139,
      139,  139,  139,  139,  139,  140,  141,  141,  141,  141,
      141,  141,  141,  141,  141,  142,  143,  143,  143,  143,
      144,  145,  145,  145,  145,  145,  146,  147,  148,  148,
      148,  148,  148,  148,  148,  149,  149,  150,  150,  150,
      150,  150,  150,  150,  151,  151,  151,  151,  151,  151,
      151,  151,  152,  153,  153,  153,  154,  154,  154,  154,
      155,  155,  156,  156,  156,  156,  156,  156,  156,  156,
      157,  158,  159,  159,  159,  159,  159,  159,  159,  159,
      160,  160,  160,  161,  161,  161,  161,  161,  161,  161,

      162,  162,  162,  162,  162,  162,  163,  163,  163,  163,
      163,  163,  163,  164,  164,  165,  165,  166,  166,  166,
      166,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      166,  166,  166,  166,  166,  166,  166,  167,  167,  168,
      168,  168,  168,  168,  168,  168,  168,  169,  169,  170,
      170,  170,  170,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  172,  173,  173,  173,  174,  174,  174,
      174,  175,  175,  176,  177,  177,  177,  177,  177,  177,
      177,  177,  177,  177,  177,  178,  178,  179,  179,  179,
      180,  180,  180,  180,  180,  181,  182,  182,  182,  182,

      182,  182,  182,  183,  184,  184,  185,  186,  187,  187,
      187,  187,  188,  188,  188,  188,  189,  190,  191,  191,
      191,  191,  191,  191,  191,  191,  192,  192,  193,  194,
      194,  195,  195,  195,  196,  196,  196,  196,  197,  197
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    2,    1,    1,    1,    1,    3,    4,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    1,    1,    1,    1,    1,    6,    1,
        1,    1,    1,    7,    8,    9,   10,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   11,
        1,   12,    1,    1,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       22,   29,   30,   31,   32,   22,   33,   22,   22,   22,
        1,    1,    1,    1,    1,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
       48,   49,   50,   51,   52,   53,   54,   55,   56,   22,
       57,   58,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[59] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    3,
        1,    1,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    5,    4,    4,
        4,    6,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4
    } ;

static const flex_int16_t yy_base[595] =
    {   0,
        0,    0,    0,    0,   58,  111,  701,  702,  702,  702,
      702,  690,   24,   30,   25,   43,   51,   40,   38,  651,
       42,  656,   53,  655,   50,   82,   61,  658,   73,   64,
       61,   85,  101,  647,  104,   82,  702,  702,  702,  689,
      702,  117,  640,  645,   97,  634,  652,  679,  676,  647,
      649,  647,  642,   43,  646,   94,  647,  643,  634,  114,
      631,  636,  642,  638,  630,  622,  625,  617,  619,   62,
      636,  624,  634,  632,  614,  614,  628,  618,  615,  627,
      622,  625,  613,  113,   89,  111,  606,  605,  617,  117,
      602,  120,  616,  609,  702,  604,    0,  129,  608,  596,

        0,  608,  609,  594,  598,  632,  702,  592,  170,  173,
      605,  176,  179,  601,  594,  586,  604,  585,  588,  591,
      589,  581,  585,  578,  588,  582,  583,  591,  575,  587,
      571,  578,  588,  138,  576,  565,  562,  564,  564,  571,
        0,  573,  568,  562,  576,  569,  562,  571,  571,  565,
      561,  571,  562,  552,  186,  564,  547,  562,    0,  702,
        0,  551,  702,  550,    0,  702,    0,    0,  555,    0,
      562,  542,  702,  546,  545,  172,  168,  554,  553,  539,
        0,  536,  552,  582,  538,  547,  536,  535,  529,  190,
      547,  546,  539,  527,  543,  542,  538,    0,  702,  536,

      535,  538,  524,  529,  531,  702,  519,  533,  513,  527,
      528,  149,  516,  528,  510,  518,  512,  524,  509,  176,
      198,  505,  503,  501,  702,  702,  506,  505,  702,  702,
      702,  499,  702,  495,  508,  494,  494,  492,  511,  491,
      496,  508,  702,  490,  489,  524,  492,  490,  490,  484,
      481,  179,  498,  487,  493,  483,  489,  482,  702,  702,
      702,  490,  517,    0,  488,  201,  490,  472,  702,  481,
      475,  463,  485,  465,  477,  470,  473,  468,    0,    0,
      462,  465,  455,  702,  457,  702,    0,    0,    0,  475,
      470,  456,  468,  453,  467,    0,  451,    0,  454,  467,

      459,  465,  445,  455,    0,  458,  461,  452,  205,  488,
      446,  453,  452,    0,  702,  702,  451,  465,  436,  448,
      434,  450,    0,  430,  702,  702,    0,  430,  439,  702,
      702,  438,  426,  440,  435,  702,  702,  702,  423,    0,
        0,    0,  433,  173,  702,  420,  702,  416,  419,  433,
      434,  427,  432,  702,  416,  419,  420,  415,  202,  425,
        0,  702,  702,  411,  413,  702,  408,  411,  414,  702,
        0,  702,  404,  408,  400,  411,  395,  404,  402,  702,
      702,  702,  390,  387,  380,  390,  172,  378,  365,  702,
      372,  222,  702,  379,  371,  362,  353,  399,  354,  702,

      346,  345,  355,  334,  349,  702,    0,  352,  331,  330,
      340,  333,  702,  334,  702,  335,  702,  329,  327,    0,
      322,    0,  317,  177,    0,  316,  298,  303,  293,  309,
      286,  283,  296,  284,    0,  277,  702,  280,  702,  275,
        0,  281,  264,  260,    0,  227,  702,  253,  702,    0,
      269,  251,  702,  264,  241,  255,  254,  287,  231,  185,
      238,  218,  702,  702,    0,  232,  702,  232,  216,  229,
      702,  189,  702,  702,  227,  223,    0,    0,  228,  258,
      248,  222,  213,  211,    0,    0,  702,  205,    0,    0,
        0,  223,  208,  209,  702,  702,  197,  223,  198,  209,

      213,  212,  702,  702,    0,  702,  702,  702,  197,  196,
      192,  702,  194,  192,  206,  702,  702,  702,  188,  194,
      194,  228,  195,  201,  177,  702,  169,  702,  702,  168,
        0,  160,  119,  702,   87,   31,    0,  702,  702,  274,
      278,  284,  290,  293,  299,  302,  305,  308,  311,  314,
      317,  320,  323,  326,  329,  332,  337,  340,  343,  346,
      349,  352,  355,  358,  361,  364,  367,  370,  373,  376,
      379,  382,  388,  391,  394,  399,  402,  405,  408,  411,
      414,  417,  420,  423,  426,  429,  432,  435,  438,  441,
      444,  447,  450,  453

    } ;

static const flex_int16_t yy_def[595] =
    {   0,
      539,    1,    1,    1,  540,  540,  539,  539,  539,  539,
      539,  541,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  541,  542,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  543,  539,  544,  539,

      545,  539,  539,  539,  539,  542,  539,  539,  539,  546,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      547,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  548,  539,
      549,  539,  539,  539,  550,  539,  551,  552,  539,  553,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      554,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  555,  539,  556,

      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  557,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  558,  559,
      539,  539,  539,  539,  539,  539,  560,  561,  562,  539,
      539,  539,  539,  539,  539,  563,  539,  564,  539,  539,

      539,  539,  539,  539,  565,  539,  539,  539,  539,  539,
      539,  539,  539,  566,  539,  539,  539,  539,  539,  539,
      539,  539,  567,  539,  539,  539,  568,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  569,
      570,  571,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  572,  539,  539,  539,  539,  539,  539,  539,  539,
      573,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      574,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  575,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,

      539,  539,  539,  539,  539,  539,  576,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  577,
      539,  578,  539,  539,  579,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  580,  539,  539,  539,  539,  539,
      581,  539,  539,  539,  582,  539,  539,  539,  539,  583,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  584,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  585,  586,  539,  539,
      539,  539,  539,  539,  587,  588,  539,  539,  589,  590,
      591,  539,  539,  539,  539,  539,  539,  539,  539,  539,

      539,  539,  539,  539,  592,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      593,  539,  539,  539,  539,  539,  594,  539,    0,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539

    } ;

static const flex_int16_t yy_nxt[761] =
    {   0,
        8,    9,    8,   10,    8,   11,    8,    8,    8,    8,
       12,    8,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   11,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   11,   32,   14,   15,   33,   17,   18,   34,
       20,   21,   11,   22,   23,   24,   35,   26,   27,   11,
       28,   29,   30,   36,   11,   11,   11,   11,   37,   38,
       37,   39,   37,   50,   40,   37,   41,   37,   37,   37,
       51,   54,   56,   65,   52,   67,   53,  537,   57,   58,
       59,   66,  112,   55,   60,   68,   61,   62,   70,  113,
       73,   42,   71,   43,   74,   44,   63,   76,   82,   45,

      132,   88,   46,   77,   89,   64,   85,   90,   83,   91,
       47,   37,   38,   37,   39,   37,  133,   40,   37,   41,
       37,   37,   37,   78,   50,  149,   86,   79,   94,   87,
       91,   51,  101,   80,  536,   52,   81,   58,   59,  115,
      116,  150,   92,  102,   42,  151,   43,  152,   44,  120,
       93,   76,   45,  156,  103,   46,   53,   77,   96,  157,
      535,   97,  121,   47,  147,  122,  161,  148,  121,   98,
      162,  122,  172,  172,  172,  174,  174,  174,  176,  176,
      176,  177,  177,  177,  198,  238,  177,  199,  220,  220,
      220,  239,  252,  252,  252,  273,  282,  252,  307,  274,

      283,  283,  283,  318,  318,  318,  238,  358,  358,  358,
      384,  526,  239,  419,  384,  397,  492,  282,  483,  307,
      533,  398,  532,  420,  424,  424,  424,  451,  452,  472,
      472,  472,  484,  531,  530,  529,  528,  492,  527,  526,
      525,  524,  221,  523,  522,  521,  520,  519,  517,  516,
      515,  514,  513,  512,  511,  510,  509,  505,  502,  501,
      500,  499,  498,  497,  494,  493,  491,  490,  489,  488,
      486,  485,  482,  425,    8,    8,    8,    8,    8,    8,
       49,   49,   49,   49,  106,  106,  106,  106,  106,  106,
      160,  481,  160,  163,  480,  163,  479,  478,  163,  166,

      477,  166,  173,  476,  173,  206,  475,  206,  225,  473,
      225,  226,  470,  226,  229,  469,  229,  230,  468,  230,
      231,  466,  231,  233,  465,  233,  243,  464,  243,  260,
      462,  260,  261,  461,  261,  460,  261,  316,  459,  316,
      330,  458,  330,  331,  457,  331,  336,  456,  336,  337,
      455,  337,  338,  454,  338,  345,  450,  345,  347,  448,
      347,  354,  446,  354,  363,  445,  363,  370,  444,  370,
      372,  443,  372,  380,  442,  380,  381,  441,  381,  382,
      440,  382,  390,  439,  390,  438,  436,  390,  400,  435,
      400,  406,  434,  406,  417,  433,  417,  432,  417,  437,

      431,  437,  447,  430,  447,  449,  429,  449,  453,  428,
      453,  463,  427,  463,  467,  426,  467,  471,  423,  471,
      474,  422,  474,  487,  421,  487,  495,  418,  495,  496,
      416,  496,  503,  415,  503,  504,  414,  504,  506,  413,
      506,  507,  412,  507,  508,  411,  508,  518,  410,  518,
      534,  409,  534,  538,  408,  538,  407,  405,  404,  403,
      402,  401,  399,  396,  395,  394,  393,  392,  391,  389,
      388,  387,  386,  385,  383,  379,  378,  377,  376,  375,
      374,  373,  371,  369,  368,  367,  366,  365,  364,  362,
      361,  360,  359,  357,  356,  355,  353,  352,  351,  350,

      349,  348,  346,  344,  343,  342,  341,  340,  339,  335,
      334,  333,  332,  329,  328,  327,  326,  325,  324,  323,
      322,  321,  320,  319,  317,  315,  314,  313,  312,  311,
      310,  309,  308,  306,  305,  304,  303,  302,  301,  300,
      299,  298,  297,  296,  295,  294,  293,  292,  291,  290,
      289,  288,  287,  286,  285,  284,  281,  280,  279,  278,
      277,  276,  275,  272,  271,  270,  269,  268,  267,  266,
      265,  264,  263,  262,  259,  258,  257,  256,  255,  254,
      253,  251,  250,  249,  248,  247,  246,  245,  244,  242,
      241,  240,  237,  236,  235,  234,  232,  228,  227,  224,

      223,  222,  219,  218,  217,  216,  215,  214,  213,  212,
      211,  210,  209,  208,  207,  205,  204,  203,  202,  201,
      200,  197,  196,  195,  194,  193,  192,  191,  190,  189,
      188,  187,  186,  185,  184,  183,  182,  181,  180,  179,
      178,  175,  171,  107,  170,  169,  168,  167,  165,  164,
      159,  157,  156,  158,  155,  154,  153,  146,  145,  144,
      143,  142,  141,  140,  139,  138,  137,  136,  135,  134,
      131,  130,  129,  128,  127,  126,  125,  124,  123,  119,
      118,  117,  114,  111,  110,  109,  108,  107,  539,  105,
      104,  100,   99,   95,   68,   84,   75,   72,   69,   48,

      539,    7,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539
    } ;

static const flex_int16_t yy_chk[761] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    5,
        5,    5,    5,   13,    5,    5,    5,    5,    5,    5,
       13,   14,   15,   18,   13,   19,   13,  536,   15,   16,
       16,   18,   54,   14,   16,   19,   17,   17,   21,   54,
       23,    5,   21,    5,   23,    5,   17,   25,   27,    5,

       70,   30,    5,   25,   30,   17,   29,   31,   27,   31,
        5,    6,    6,    6,    6,    6,   70,    6,    6,    6,
        6,    6,    6,   26,   32,   85,   29,   26,   36,   29,
       36,   32,   45,   26,  535,   32,   26,   33,   33,   56,
       56,   85,   33,   45,    6,   86,    6,   86,    6,   60,
       35,   35,    6,   90,   45,    6,   35,   35,   42,   90,
      533,   42,   60,    6,   84,   60,   98,   84,   92,   42,
       98,   92,  109,  109,  109,  110,  110,  110,  112,  112,
      112,  113,  113,  113,  134,  176,  113,  134,  155,  155,
      155,  177,  190,  190,  190,  212,  220,  190,  252,  212,

      221,  221,  221,  266,  266,  266,  176,  309,  309,  309,
      344,  532,  177,  387,  344,  359,  472,  220,  460,  252,
      530,  359,  527,  387,  392,  392,  392,  424,  424,  446,
      446,  446,  460,  525,  524,  523,  522,  472,  521,  520,
      519,  515,  155,  514,  513,  511,  510,  509,  502,  501,
      500,  499,  498,  497,  494,  493,  492,  488,  484,  483,
      482,  481,  480,  479,  476,  475,  470,  469,  468,  466,
      462,  461,  459,  392,  540,  540,  540,  540,  540,  540,
      541,  541,  541,  541,  542,  542,  542,  542,  542,  542,
      543,  458,  543,  544,  457,  544,  456,  455,  544,  545,

      454,  545,  546,  452,  546,  547,  451,  547,  548,  448,
      548,  549,  444,  549,  550,  443,  550,  551,  442,  551,
      552,  440,  552,  553,  438,  553,  554,  436,  554,  555,
      434,  555,  556,  433,  556,  432,  556,  557,  431,  557,
      558,  430,  558,  559,  429,  559,  560,  428,  560,  561,
      427,  561,  562,  426,  562,  563,  423,  563,  564,  421,
      564,  565,  419,  565,  566,  418,  566,  567,  416,  567,
      568,  414,  568,  569,  412,  569,  570,  411,  570,  571,
      410,  571,  572,  409,  572,  408,  405,  572,  573,  404,
      573,  574,  403,  574,  575,  402,  575,  401,  575,  576,

      399,  576,  577,  398,  577,  578,  397,  578,  579,  396,
      579,  580,  395,  580,  581,  394,  581,  582,  391,  582,
      583,  389,  583,  584,  388,  584,  585,  386,  585,  586,
      385,  586,  587,  384,  587,  588,  383,  588,  589,  379,
      589,  590,  378,  590,  591,  377,  591,  592,  376,  592,
      593,  375,  593,  594,  374,  594,  373,  369,  368,  367,
      365,  364,  360,  358,  357,  356,  355,  353,  352,  351,
      350,  349,  348,  346,  343,  339,  335,  334,  333,  332,
      329,  328,  324,  322,  321,  320,  319,  318,  317,  313,
      312,  311,  310,  308,  307,  306,  304,  303,  302,  301,

      300,  299,  297,  295,  294,  293,  292,  291,  290,  285,
      283,  282,  281,  278,  277,  276,  275,  274,  273,  272,
      271,  270,  268,  267,  265,  263,  262,  258,  257,  256,
      255,  254,  253,  251,  250,  249,  248,  247,  246,  245,
      244,  242,  241,  240,  239,  238,  237,  236,  235,  234,
      232,  228,  227,  224,  223,  222,  219,  218,  217,  216,
      215,  214,  213,  211,  210,  209,  208,  207,  205,  204,
      203,  202,  201,  200,  197,  196,  195,  194,  193,  192,
      191,  189,  188,  187,  186,  185,  184,  183,  182,  180,
      179,  178,  175,  174,  172,  171,  169,  164,  162,  158,

      157,  156,  154,  153,  152,  151,  150,  149,  148,  147,
      146,  145,  144,  143,  142,  140,  139,  138,  137,  136,
      135,  133,  132,  131,  130,  129,  128,  127,  126,  125,
      124,  123,  122,  121,  120,  119,  118,  117,  116,  115,
      114,  111,  108,  106,  105,  104,  103,  102,  100,   99,
       96,   94,   93,   91,   89,   88,   87,   83,   82,   81,
       80,   79,   78,   77,   76,   75,   74,   73,   72,   71,
       69,   68,   67,   66,   65,   64,   63,   62,   61,   59,
       58,   57,   55,   53,   52,   51,   50,   49,   48,   47,
       46,   44,   43,   40,   34,   28,   24,   22,   20,   12,

        7,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539
    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "dubya.l"
/* GNU Talkfilters
   Copyright (C) 1998-2003 Free Software Foundation, Inc.

   This file is part of GNU Talkfilters

   GNU Talkfilters is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License as
   published by the Free Software Foundation; either version 2, or (at
   your option) any later version.

   This software is distributed in the hope that it will be amusing, but
   WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this software; see the file COPYING.  If not, write to the
   Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
*/
#line 35 "dubya.l"

#include "common.h"
#include "talkfilters.h"

#define YY_DECL int yylex(gtf_databuf_t *buf)

#line 1124 "dubya.c"

#line 1126 "dubya.c"

#define INITIAL 0
#define NIW 1
#define INW 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 50 "dubya.l"


#line 1354 "dubya.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 540 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 702 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 54 "dubya.l"
gtf_echo(); /* don't damage HTML tags */
	YY_BREAK
case 2:
#line 57 "dubya.l"
case 3:
#line 58 "dubya.l"
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 58 "dubya.l"
{ switch(gtf_random(3))
				  {
				  case 0: gtf_puts_case("bad guy"); break;
				  case 1: gtf_puts_case("evildoer"); break;
				  case 2: gtf_puts_case("terrier"); break;
				  }
				}
	YY_BREAK
case 5:
/* rule 5 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 11);
(yy_c_buf_p) = yy_cp = yy_bp + 11;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 65 "dubya.l"
gtf_puts_case("pre-emptive");
	YY_BREAK
case 6:
/* rule 6 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 6);
(yy_c_buf_p) = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 66 "dubya.l"
gtf_puts_case("freedom-fighter");
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 67 "dubya.l"
gtf_puts_case("misunder"); BEGIN(INW);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 68 "dubya.l"
gtf_puts_case("misunderestimate"); BEGIN(INW);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 69 "dubya.l"
gtf_puts_case("misunderestimated"); BEGIN(INW);
	YY_BREAK
case 10:
/* rule 10 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 4);
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 70 "dubya.l"
gtf_puts_case("oblitifry");
	YY_BREAK
case 11:
/* rule 11 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 6);
(yy_c_buf_p) = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 71 "dubya.l"
gtf_puts_case("oblitifried");
	YY_BREAK
case 12:
/* rule 12 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 8);
(yy_c_buf_p) = yy_cp = yy_bp + 8;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 72 "dubya.l"
gtf_puts_case("destructifry");
	YY_BREAK
case 13:
/* rule 13 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 10);
(yy_c_buf_p) = yy_cp = yy_bp + 10;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 73 "dubya.l"
gtf_puts_case("destructifried");
	YY_BREAK
case 14:
/* rule 14 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 7);
(yy_c_buf_p) = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 74 "dubya.l"
gtf_puts_case("resignat");
	YY_BREAK
case 15:
/* rule 15 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 75 "dubya.l"
gtf_puts_case("foreign-handed");
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 76 "dubya.l"
gtf_puts_case("embetter"); BEGIN(INW);
	YY_BREAK
case 17:
/* rule 17 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 11);
(yy_c_buf_p) = yy_cp = yy_bp + 11;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 77 "dubya.l"
gtf_puts_case("fallacy");
	YY_BREAK
case 18:
/* rule 18 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 7);
(yy_c_buf_p) = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 78 "dubya.l"
gtf_puts_case("anecdote");
	YY_BREAK
case 19:
/* rule 19 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 10);
(yy_c_buf_p) = yy_cp = yy_bp + 10;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 79 "dubya.l"
gtf_puts_case("subliminabable");
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 80 "dubya.l"
gtf_puts_case("pacemaker"); BEGIN(INW);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 81 "dubya.l"
gtf_puts_case("liberat"); BEGIN(INW);
	YY_BREAK
case 22:
/* rule 22 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 7);
(yy_c_buf_p) = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 82 "dubya.l"
gtf_puts_case("hostile");
	YY_BREAK
case 23:
/* rule 23 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 12);
(yy_c_buf_p) = yy_cp = yy_bp + 12;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 83 "dubya.l"
gtf_puts_case("commiserate");
	YY_BREAK
case 24:
/* rule 24 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 6);
(yy_c_buf_p) = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 84 "dubya.l"
gtf_puts_case("soddam");
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 85 "dubya.l"
gtf_puts_case("nucular"); BEGIN(INW);
	YY_BREAK
case 26:
/* rule 26 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 9);
(yy_c_buf_p) = yy_cp = yy_bp + 9;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 86 "dubya.l"
gtf_puts_case("a preemptive military strike"); BEGIN(INW);
	YY_BREAK
case 27:
/* rule 27 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 9);
(yy_c_buf_p) = yy_cp = yy_bp + 9;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 87 "dubya.l"
gtf_puts_case("change");
	YY_BREAK
case 28:
/* rule 28 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 19);
(yy_c_buf_p) = yy_cp = yy_bp + 19;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 88 "dubya.l"
gtf_puts_case("regime");
	YY_BREAK
case 29:
/* rule 29 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 3);
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
#line 90 "dubya.l"
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 90 "dubya.l"
{ switch(gtf_random(3))
			         {
			         case 0: gtf_puts_case("freedom"); break;
			         case 1: gtf_puts_case("democracy"); break;
			         case 2: gtf_puts_case("liberty"); break;
			         }
			     }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 97 "dubya.l"
gtf_puts_case("Eyeraq"); BEGIN(INW);
	YY_BREAK
case 32:
/* rule 32 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 4);
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
#line 99 "dubya.l"
case 33:
/* rule 33 can match eol */
#line 100 "dubya.l"
case 34:
/* rule 34 can match eol */
#line 101 "dubya.l"
case 35:
/* rule 35 can match eol */
#line 102 "dubya.l"
case 36:
/* rule 36 can match eol */
#line 103 "dubya.l"
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 103 "dubya.l"
{ switch(gtf_random(5))
				 {
				 case 0: gtf_puts_case("a rogue state");
                                         break;
				 case 1: gtf_puts_case("a failed nation");
                                         break;
				 case 2: gtf_puts_case("a nation in the axis of evil");
                                         break;
				 case 3: gtf_puts_case("an enemy of freedom");
                                         break;
				 case 4: gtf_puts_case("a state sponsor of terrorism");
                                         break;
				 }
			     }
	YY_BREAK
case 38:
/* rule 38 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 6);
(yy_c_buf_p) = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 117 "dubya.l"
gtf_puts_case("lot of numbers");
	YY_BREAK
case 39:
/* rule 39 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 9);
(yy_c_buf_p) = yy_cp = yy_bp + 9;
YY_DO_BEFORE_ACTION; /* set up yytext again */
#line 119 "dubya.l"
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 119 "dubya.l"
gtf_puts_case("the Party o' Cut n' Run");
	YY_BREAK
case 41:
/* rule 41 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 3);
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 120 "dubya.l"
gtf_puts_case("is");
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 121 "dubya.l"
gtf_puts_case("retort"); BEGIN(INW);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 122 "dubya.l"
gtf_puts_case("justic"); BEGIN(INW);
	YY_BREAK
case 44:
/* rule 44 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 9);
(yy_c_buf_p) = yy_cp = yy_bp + 9;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 123 "dubya.l"
gtf_puts_case("them were");
	YY_BREAK
case 45:
/* rule 45 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 6);
(yy_c_buf_p) = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 124 "dubya.l"
gtf_puts_case("policy stuff");
	YY_BREAK
case 46:
/* rule 46 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 7);
(yy_c_buf_p) = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 125 "dubya.l"
gtf_puts_case("is our");
	YY_BREAK
case 47:
/* rule 47 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 12);
(yy_c_buf_p) = yy_cp = yy_bp + 12;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 126 "dubya.l"
gtf_puts_case("dark dungeons of the Innurnet");
	YY_BREAK
case 48:
/* rule 48 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 11);
(yy_c_buf_p) = yy_cp = yy_bp + 11;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 127 "dubya.l"
gtf_puts_case("hemispheric");
	YY_BREAK
case 49:
/* rule 49 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 8);
(yy_c_buf_p) = yy_cp = yy_bp + 8;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 128 "dubya.l"
gtf_puts_case("garbage man");
	YY_BREAK
case 50:
/* rule 50 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 6);
(yy_c_buf_p) = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 129 "dubya.l"
gtf_puts_case("fucking son of a bitch");
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 130 "dubya.l"
gtf_puts("Big Dick");
	YY_BREAK
case 52:
#line 132 "dubya.l"
case 53:
YY_RULE_SETUP
#line 132 "dubya.l"
gtf_puts("Daddy"); BEGIN(INW);
	YY_BREAK
case 54:
#line 134 "dubya.l"
case 55:
#line 135 "dubya.l"
case 56:
YY_RULE_SETUP
#line 135 "dubya.l"
gtf_puts_case("vulcanize"); BEGIN(INW);
	YY_BREAK
case 57:
/* rule 57 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 7);
(yy_c_buf_p) = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 136 "dubya.l"
gtf_puts_case("Anti-Americanism");
	YY_BREAK
case 58:
/* rule 58 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 10);
(yy_c_buf_p) = yy_cp = yy_bp + 10;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 137 "dubya.l"
gtf_puts_case("Unpatriotic");
	YY_BREAK
case 59:
/* rule 59 can match eol */
#line 139 "dubya.l"
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 139 "dubya.l"
gtf_puts_case("Tax cuts"); BEGIN(INW);
	YY_BREAK
case 61:
/* rule 61 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 9);
(yy_c_buf_p) = yy_cp = yy_bp + 9;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 140 "dubya.l"
gtf_puts_case("Reaganomics");
	YY_BREAK
case 62:
/* rule 62 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 7);
(yy_c_buf_p) = yy_cp = yy_bp + 7;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 141 "dubya.l"
gtf_puts_case("And -- but first things first. The -- These");
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 142 "dubya.l"
gtf_puts_case("cut n' run.");
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 144 "dubya.l"
{ BEGIN(INW); gtf_echo(); }
	YY_BREAK


case 65:
/* rule 65 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 2);
(yy_c_buf_p) = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 149 "dubya.l"
gtf_puts_case("ically"); BEGIN(NIW);
	YY_BREAK
case 66:
/* rule 66 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 2);
(yy_c_buf_p) = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 150 "dubya.l"
gtf_puts_case("abable"); BEGIN(NIW);
	YY_BREAK
case 67:
/* rule 67 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 3);
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 151 "dubya.l"
gtf_puts_case("atify"); BEGIN(NIW);
	YY_BREAK
case 68:
/* rule 68 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 5);
(yy_c_buf_p) = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 152 "dubya.l"
gtf_puts_case("atification"); BEGIN(NIW);
	YY_BREAK
case 69:
/* rule 69 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 2);
(yy_c_buf_p) = yy_cp = yy_bp + 2;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 153 "dubya.l"
gtf_puts_case("ctify"); BEGIN(NIW);
	YY_BREAK
case 70:
/* rule 70 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 5);
(yy_c_buf_p) = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 154 "dubya.l"
gtf_puts_case("ctification"); BEGIN(NIW);
	YY_BREAK
case 71:
/* rule 71 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 3);
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 155 "dubya.l"
gtf_puts_case("ainify"); BEGIN(NIW);
	YY_BREAK
case 72:
/* rule 72 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 3);
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 156 "dubya.l"
gtf_puts_case("entification");
	YY_BREAK
case 73:
/* rule 73 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 3);
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 157 "dubya.l"
gtf_puts_case("tenify"); BEGIN(NIW);
	YY_BREAK
case 74:
/* rule 74 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 3);
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 158 "dubya.l"
gtf_puts_case("izification"); BEGIN(NIW);
	YY_BREAK
case 75:
/* rule 75 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 5);
(yy_c_buf_p) = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 159 "dubya.l"
gtf_puts_case("lyzation"); BEGIN(NIW);
	YY_BREAK
case 76:
/* rule 76 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_bp + 3);
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 160 "dubya.l"
gtf_puts_case("in'"); BEGIN(NIW);
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 161 "dubya.l"
{ switch(gtf_random(10))
		    {
		    case 0: gtf_puts_case(". Yee haw!"); break;
                    case 1: gtf_puts_case(", by golly."); break;
                    case 2:
                    case 3: gtf_puts_case(". Stay the course!"); break;
                    case 4: gtf_puts_case(". I'm the decider!"); break;
		    default: gtf_echo();
		    }
                  BEGIN(NIW);
		}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 172 "dubya.l"
{ switch(gtf_random(5))
                    {
                    case 0: gtf_puts(" -- I think -- "); break;
                    case 1: gtf_puts(" -- I mean -- "); break;
                    case 2: gtf_puts(", and uhh... umm..., "); break;
                    default: gtf_echo();
                    }
                }
	YY_BREAK
case 79:
/* rule 79 can match eol */
YY_RULE_SETUP
#line 181 "dubya.l"
BEGIN(NIW); gtf_unput_last();
	YY_BREAK

case 80:
YY_RULE_SETUP
#line 185 "dubya.l"
/* ignore trailing EOT character */
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 186 "dubya.l"
gtf_echo();
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 188 "dubya.l"
ECHO;
	YY_BREAK
#line 2088 "dubya.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(NIW):
			case YY_STATE_EOF(INW):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 540 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 540 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 539);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 188 "dubya.l"


#ifdef LIBRARY_MODE

int gtf_filter_dubya(const char *input, char *buf, size_t bufsz)
  {
  gtf_databuf_t buffer;
  YY_BUFFER_STATE _yybuf;

  gtf_strbuf_init(&buffer, buf, bufsz);
  _yybuf = yy_scan_string(input);
  yylex(&buffer);
  yy_delete_buffer(_yybuf);
  gtf_reset();

  return(buffer.overflow);
  }

int __gtf_filter_dubya(const char *input, char *buf, size_t bufsz)
{
  return(gtf_filter_dubya(input, buf, bufsz));
}

#else /* LIBRARY_MODE */

int main(int argc, char **argv)
  {
  gtf_parse_args();
  gtf_random_seed();

  yylex(NULL);

  return(EXIT_SUCCESS);
  }

#endif /* LIBRARY_MODE */

/* end of source file */

